- sample_app_metadata/wayland-egl-test.json
- templates/generic/rpi3.json
Enable user namespacing again on the Pi with the correct UID/GID
> Update RPi template

- bundlegen/core/stb_platform.py
- sample_app_metadata/flutter_reference.json
- sample_app_metadata/youi_reference.json
- templates/generic/rpi3_reference.json
- templates/lgi/7218c_reference.json
* also fix lookup of matching platform json files
(without this, --platform rpi3 will also match with rpi3_reference.json)
> Add support for reference image targets

- bundlegen/core/bundle_processor.py
- templates/generic/rpi3_reference.json
- templates/lgi/7218c_reference.json
* also update handling of gfxLibs to remove libs from
rootfs if existing there (like what happens with libs
in pluginDependencies)
> Support for essos and wayland-egl-input dac images

- test/build_and_test_on_7218c.sh
- test/build_and_test_on_rpi.sh
- test/testapp.sh
Examples:
Test already generated bundle:
./test/testapp.sh 192.168.1.124 rpi-dac-image-wayland-egl-test.tar.gz
Generate bundle and test it:
./test/build_and_test_on_rpi.sh 192.168.1.124 dac-image-wayland-egl-test.tar
> Add scripts to test generated bundle quickly on target

- .gitignore
- README.md
- Vagrantfile
Automatically clone/install bundlegen when creating the VM
> Updated README and vagrantfile

- bundlegen/cli/main.py
- bundlegen/core/utils.py
Use create_ipk instead of create_tgz in main to switch between modes.
> Added support for generating ipk package instead of simple tarballs.

- templates/generic/rpi3_reference.json
- templates/generic/rpi3_reference_libs.json
Signed-off-by: Damian Wrobel <dwrobel@ertelnet.rybnik.pl>
> Update reference platform files

- test/testapp.sh
Signed-off-by: Damian Wrobel <dwrobel@ertelnet.rybnik.pl>
> Improve testapp.sh script

- bundlegen/core/capabilities.py
- docker/start.sh
- test/build_and_test.sh
- test/build_and_test_on_7218c.sh
- test/build_and_test_on_7218c_dunfell.sh
- test/build_and_test_on_rpi.sh
- test/build_and_test_on_rpi_dunfell.sh
- test/testapp.sh
- webui/app.py
- webui/static/index.js
Reason for change: Updated Consult Red apache headers
Test Procedure: Jenkin build should pass
Risks: None
> BD-963:Compliance Tidy-Up in BundleGen

- templates/lgi/ah212_reference.json
- templates/lgi/ah212_reference_libs.json
- test/build_and_test.sh
- test/build_and_test_on_ah212.sh
* also works for amlogic Skyworth HP44H
> Add amlogic AH212 template

- bundlegen/core/bundle_processor.py
* make sure it accepts an empty array of capabilities
> Add posibility to set no capabilities

- bundlegen/cli/main.py
- bundlegen/core/utils.py
- docs/Templates.md
* use process.user uid/gid for ownership of files while
making tarball
* support file mask to remove certain rights from
files while making tarball
> Support tarballing options:

- test/build_and_test.sh
- test/build_and_test_on_7218c.sh
- test/build_and_test_on_7218c_dunfell.sh
- test/build_and_test_on_ah212.sh
- test/build_and_test_on_rpi.sh
- test/build_and_test_on_rpi_dunfell.sh
- test/build_and_test_on_rtd1319.sh
Simplify TARGET and TARGET_VERSION into one param TEMPLATE
> Update test scripts

- templates/generic/rpi3_reference_dunfell.json
- templates/generic/rpi3_reference_dunfell_libs.json
- templates/lgi/7218c_reference_dunfell.json
- templates/lgi/7218c_reference_dunfell_libs.json
* also add support for cobalt+rialto DAC app
> Update templates for dunfell reference RPI and 7218c targets

- bundlegen/rabbitmq/message_handler.py
- bundlegen/rabbitmq/test/test.py
* also update test.py for the new message parameters
> Add tarball settings processing to rabbit mq handler

- test/build_and_test.sh
- test/testapp_lisa.sh
* still supports Packager
* auto-detects between both but prefers LISA if running
> test scripts: support LISA for installing DAC apps

- bundlegen/cli/main.py
- bundlegen/core/bundle_processor.py
- test/build_and_test.sh
* previously there was a warning but it proceeded anyway
now it reports error and returns False and stops
* also make sure to return with exit code in cli
* update test script to check for this and avoid
trying to test failed bundle on the box
> ONEM-25444 Refuse unsupported network type

- bundlegen/core/bundle_processor.py
- docs/Templates.md
* moved some checks for persistent storage to _compatibility_check()
* added check for maxTotalSize
* added (optional) checks for temporary storages
> ONEM-25444 Check persistent and temp storage limits

- templates/generic/rpi3_reference_vc4_dunfell.json
- templates/generic/rpi3_reference_vc4_dunfell_libs.json
- test/build_and_test.sh
* needs /dev/dri/card0 and /usr/lib/dri/vc4_dri.so
* also include small fix to build_and_test.sh so that the
EXTRA_OPTIONS are put last in arg list: this allows override
of preceding parameters.
> Add template for RPI3 VC4 dunfell

- webui/app.py
Taking the changes from https://github.com/rdkcentral/BundleGen/pull/68 and creating the new pull request.
> CVE-2007-4559 - Creating a patch

- templates/generic/rpi3_reference.json
- templates/generic/rpi3_reference_dunfell.json
- templates/generic/rpi3_reference_vc4_dunfell.json
Removing the maxRam_disabled from the generic platform config JSONs as per discussion with Gurdal & Stephen
> Remove the maxRam_disabled from platfrom config

- .github/workflows/L1-unit_tests.yml
As part of this pull request, added the workflow changes for L1 unit testing
> [RDK-35868] - Add unit tests to BundleGen

- templates/generic/rpi3_reference_dunfell.json
- templates/generic/rpi3_reference_vc4_dunfell.json
- templates/lgi/72127ott_reference_dunfell.json
- templates/lgi/7218c_reference_dunfell.json
Storage path of apps installed in reference image was updated because of https://code.rdkcentral.com/r/c/components/generic/rdk-oe/meta-cmf-video/+/80073
> Update storage dir path in reference image templates

- bundlegen/core/bundle_processor.py
- docs/AppMetadata.md
- docs/Templates.md
- unit_tests/L1_testing/test_files/test_Bundleprocessor_ut.py
Revised the code to support the latest dobby functionality.
> Updates to  support latest Dobby functionality

- bundlegen/schema/platformSchema.json
Amending platform schema changes that were absent
> Adding Seccomp & Apparmor support in Schema

- .github/workflows/L2-unit_tests.yml
- templates/generic/rpi3_reference_vc4_dunfell_test.json
- templates/generic/rpi3_reference_vc4_dunfell_test_libs.json
- unit_tests/L2_testing/README.md
- unit_tests/L2_testing/dac-image-wayland-egl-test-appmetadata.json
- unit_tests/L2_testing/run_L2_test.py
- unit_tests/L2_testing/test_bundle.py
Enhanced the L2 test with the optional fields.
For testing this optional fields used dummy value in platform json and appmetadata json
> Enhancing the L2 test to support optional fields

- LICENSE
- NOTICE
- webui/app.py
BD-1196 - Add credit in Bundlegen
> BD-1196 Add credit in Bundlegen

- templates/lgi/7218c_reference_dunfell.json
- templates/lgi/m393-72180ZB-stb.json
- templates/lgi/m393-72180ZB-stb_libs.json
* also update rpi3_vc4 and 7218c reference templates
> Add m393 sagem video accelerator template

- .github/workflows/L2-unit_tests.yml
- unit_tests/L1_testing/test_files/test_Bundleprocessor_ut.py
- unit_tests/L2_testing/README.md
- unit_tests/L2_testing/run_L2_test.py
enhancing the L1 testing to support few API which was not covered
> RDK-35868: Enhancing the L1_testing

- bundlegen/core/bundle_processor.py
* allows for replacing {id} inside mount.source binds with the appid from metadata or passed via cmdline
* supported in template mounts, gpu extramounts and metadata mounts
* placed into separate function _add_mount: now createmountpoints and X-mount.mkdir options also supported in all 3 places mentioned above
> ONEM-30378 Update BundleGen to support {id} in mounts

- .github/workflows/L1-unit_tests.yml
- .github/workflows/L2-unit_tests.yml
- unit_tests/L1_testing/test_files/test_Bundleprocessor_ut.py
- unit_tests/L1_testing/test_files/test_ImageDownloader_ut.py
- unit_tests/L1_testing/test_files/test_ImageUnpackager_ut.py
- unit_tests/L1_testing/test_files/test_ReadElf_ut.py
- unit_tests/L1_testing/test_files/test_STBPlatform_ut.py
- unit_tests/L1_testing/test_files/test_Utils_ut.py
- unit_tests/L2_testing/test_bundle.py
umoci was failing for the go version 1.13. so updated the go version
> Fixed the Umoci failure with updating the go version

- templates/VA/rdk-generic-mediaclient-image/RDK6/ah212_kirkstone_libs.json
Add platform_libs configuration for AH212 from kirkstone build
> Add platform_libs configuration file for AH212 from kirkstone build
