rdkcentral/BundleGen

bundlegen/cli/main.py

Add a new `-y` option to the generate command to auto-accept any prompts that occur during generation

Add -y Option to Generate

---

bundlegen/core/image_downloader.py
bundlegen/core/image_unpacker.py

* also usefull when using bundlgen in yocto build env where
skopeo and umoci are also built and provided in sysroot

Use skopeo and umoci from PATH

---

bundlegen/core/image_downloader.py

* this avoids skopeo wanting to read /etc/containers/policy.json
which is not there when building and using skopeo from inside yocto
build env
https://github.com/containers/skopeo/blob/main/docs/skopeo.1.md

Set skopeo --insecure-policy flag

---

bundlegen/core/bundle_processor.py
docs/Templates.md

* this path can include the {id} parameter which will be replaced by the id
of the app as indicated in the app metadata.
This allows BundleGen to generate the full rootfs path as it will exist on
the target platform. For example: /somewhere/run/rootfs/{id}

Support to set rootfs path and readonly property

---

bundlegen/core/bundle_processor.py
docs/Templates.md

* add process.user uid/gid to options of tmpfs temp storages
* allow fstype to be specified for persistent storages
* also support a minSize for persistent storages
(we experienced mk.xfs problem with sizes < 16MB)
Auto increment to match minSize and log warning.
* parse all (storage) sizes with option binary=True so that
1 MB really is 1MByte and not 1000000 bytes

Several updates to storages

---

bundlegen/core/bundle_processor.py

* parse all sizes with option binary=True so that
1 MB really is 1MByte (1048576 bytes) and not 1000000 bytes
* storage size parsing was already binary

Parse all sizes as binary

---

bundlegen/core/bundle_processor.py
docs/Templates.md

* Optional. If set, override the default hostname. In addition this hostname can
include the {id} parameter which will be replaced by the id of the app as
indicated in the app metadata.

Support hostname

---

bundlegen/core/bundle_processor.py

* also support terminal setting to explicitly enable or
disable a terminal
* also fix typo in journald log mode
* Dobby normally auto generates this when starting and when logging is enabled. But this change is one of several that helps with a read-only config.json

Support stdout/stderr logging annotations and terminal

---

bundlegen/rabbitmq/README.md
bundlegen/rabbitmq/message.py
bundlegen/rabbitmq/message_handler.py
bundlegen/rabbitmq/test/test.py

* add app_id to rabbitmq message so that we can override
the id inside the metadata. Handy when metadata is inside OCI
image and we only want to override the id.

ONEM-25427 add app_id override for BundleGen

---

templates/generic/rpi3_reference_dunfell.json
templates/lgi/7218c_reference_dunfell.json

* use protobuf IPC instead of dbus
* RIALTO_CLIENT_BACKEND_LIB not needed anymore
(rialto gst sink now links directly to rialtoclient)

RDKCMF-8834 support latest rialto

---

bundlegen/cli/main.py
bundlegen/core/bundle_processor.py
bundlegen/rabbitmq/message_handler.py

If the container is configured to run with user namespacing, resolve the real uid/gid when creating the tarball so permissions are set correctly.

When creating tarball, use real uid/gid if running in user namespace

---

bundlegen/cli/main.py
docs/Usage.md
templates/generic/rpi3_reference_dunfell.json
templates/lgi/7218c_reference_dunfell.json
test/build_and_test.sh

* set storage path conforming to LISA data path installation
* support overriding app id through --appid cmdline arg
(similar as with https://github.com/rdkcentral/BundleGen/commit/a1682e250f1809d274555b55183b3f5f60f662fa)
* update test scripts for this

Fix persistent storage for dac apps on reference image

---

bundlegen/core/bundle_processor.py

Currently BundleGen assigns a random string for the loopback image files.
This means if a bundle is regenerated and the app upgraded, the image name changes between the two bundles and persistent app data is lost.
Change to using a hash of the path so that images are retained providing the path inside the container doesn't change.

Ensure loopback images are retained during upgrades

---

bundlegen/core/bundle_processor.py

Activities to be done for adding seccomp support -
1. Add the seccomp field in the respective platform JSON file. This activity is pending since this information needs to be provided by Comcast/platform team.
2. Make changes in bundlegen to copy the info from platform JSON to 'linux' section of the final config JSON. This commit contains changes done for this task only

[RDK-35838] Add Seccomp support to BundleGen

---

bundlegen/core/bundle_processor.py

Activities to be done as a part of the above task -
1. Add an apparmor profile in the platform JSON file. This activity is pending since this information needs to be provided by Comcast/platform team.
2. Make changes in bundlegen to copy the apparmor profile name in the 'process' of the final config JSON during OCI bundle creation. This commit contains the changes for this task only.

[RDK-35839] Add Apparmor support to BundleGen

---

bundlegen/cli/main.py
bundlegen/core/bundle_processor.py
templates/generic/vagrant.json

By default bundlegen generates the bundle targeting DobbyTool. Running the generator with extra parameter --crun creates raw bundle, which can be run directly with crun. If app metadata refers option Dobby specific (i.e. not supported by crun e.g. storage section) then warning is printed.
Signed-off-by: Tomasz Kilarski <tomasz.kilarski@consult.red>

LCM-538: Provide option generating raw crun bundle

---

unit_tests/L1_testing/test_files/test_Bundleprocessor_ut.py

The L1_tests started failing because of the recent changes in bundle_processor.py by
PR: https://github.com/rdkcentral/BundleGen/pull/97
In PR they are replacing {id} inside mount.source binds with the appid from metadata and placed into separate function _add_mount.
In test code, because of the above update {id} was missing so added the {id} to support that in metadata.

L1 test failing for the latest changes of bundleprocessor.py file

---

bundlegen/rabbitmq/message_handler.py
docker/cli-sample/Dockerfile
docker/rabbitmq/docker-compose.yml
webui/app.py

* after this change both rabbitmq and webui are broken: LCM-538: Provide option generating raw crun bundle https://github.com/rdkcentral/BundleGen/commit/d8e95111dd23351d8a45385fc2e5fbaab8a9ea6f
* Docker cli sample has wrong WORKDIR (case sensitive) Problem seems to happen after the new schema validation feature was added (loading schema files on dirs with bad case does not work under linux)
* added a missing env var to the rabbitmq docker-compose.yml

Fix issues with rabbitmq, webui and Docker samples

---

templates/generic/rpi4_reference_dunfell.json
templates/generic/rpi4_reference_dunfell_libs.json

* target is latest reference image build for raspberrypi4-64-rdk-android-mc
* DAC apps do not start when /dev/dri/card1 missing
* DAC apps render slow (swrast) when /dev/dri/renderD128 missing
* swrast_dri.so not needed when doing vc4_dri rendering

Update RPI4 template

---

bundlegen/rabbitmq/main.py

This patch introduces a new environment variable,
RABBITMQ_HEARTBEAT_SECONDS, that controls the timing of channel heartbeat. Previously, when generating bundles took more time than set in the default heartbeat value, the bundle generator had no chance of returning a successful message due to channel closure despite successfully generating the bundle. By setting the RABBITMQ_HEARTBEAT_SECONDS environment variable, we can ensure that the channel remains open until the bundle generation is complete, thus allowing the generator to return a successful message.
Note: The default value of heartbeat that is set when environment variable is unset (60 seconds) is taken from the Pika documentation.

Add environment variable to control connection heartbeat

---

.github/workflows/L1-unit_tests.yml
.github/workflows/L2-unit_tests.yml

1	If a build server does not already have the Skopeo package, installing it.
2	During runtime, a few packages are being updated. At that moment, a yes/no option will eventually appear. so in the yml file, we are setting yes as the default.
3	If the act command is used to run yml, do not upload the coverage report to Artifactory.

Enhancing the L1 and L2 test yml script

---

templates/generic/rpi4_64_reference_bb_kirkstone.json
templates/generic/rpi4_64_reference_bb_kirkstone_libs.json
templates/generic/rpi4_reference_bb_kirkstone.json
templates/generic/rpi4_reference_bb_kirkstone_libs.json

Reason for change : Creating the json files to support RPI4 kirkstone both 32 bit and 64 bit broadband bundles
Test procedure : Created oci bundles and tested with DobbyTool
Risk : Low

REFPLTB-3201 : Create RPI4 Reference Broadband Kirkstone JSON for BundleGen templates/generic

---

templates/generic/bpir4_reference.json
templates/generic/bpir4_reference_libs.json

Reason for change : Creating the json files to support BPIR4 broadband bundles.
Test procedure : Create oci bundles and tested with DobbyTool in BPIR4 device.
Risk : Low

RDKBACCL-326: Bundlegen support for BPI R4.
